// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzreohaPh_Q1C7n5217QaO79uIMqxpBys',
    appId: '1:468552333995:web:a76267ba6e8077820a15ee',
    messagingSenderId: '468552333995',
    projectId: 'junction23-f7df7',
    authDomain: 'junction23-f7df7.firebaseapp.com',
    storageBucket: 'junction23-f7df7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiwqO7zV6kkskps5MwrDyM3i88-tTi92M',
    appId: '1:468552333995:android:1b9ac371c4e6745f0a15ee',
    messagingSenderId: '468552333995',
    projectId: 'junction23-f7df7',
    storageBucket: 'junction23-f7df7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1IacPsthn-aJk4Yq5L9MNZ5C75JDi1zQ',
    appId: '1:468552333995:ios:a7663f22a684950d0a15ee',
    messagingSenderId: '468552333995',
    projectId: 'junction23-f7df7',
    storageBucket: 'junction23-f7df7.appspot.com',
    iosBundleId: 'com.example.junction23',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1IacPsthn-aJk4Yq5L9MNZ5C75JDi1zQ',
    appId: '1:468552333995:ios:9a379a4574d871c20a15ee',
    messagingSenderId: '468552333995',
    projectId: 'junction23-f7df7',
    storageBucket: 'junction23-f7df7.appspot.com',
    iosBundleId: 'com.example.junction23.RunnerTests',
  );
}
